### ISSUE TITLE
Comments on wiki

### ISSUE THREAD

**Issue by cindyytong** [RazEfron/planet_destroyer#1]
Nice work! Some nits: 

- [x] For MVPs, please break down under each specific user stories. For example:
1. Which keys will a user click to move a player around? How will they shoot bubbles? 
2.  How will you determine where to place bubbles? 
3. Gifts: what are the options, how much, how will you determine when to put onto canvas? 
4. What factors change in each level? How many levels? How much time will there be for each level? 

- [x] Are you going to save user data that will persist across sessions? i.e. I play and get to level 3 but then I close out of the site, when I come back next should I be able to see past score and level 3? If yes, use localStorage to save scores and level. https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage 

- [x] For MVPs please map them to what you will aim to complete each day (day 1 - day 5) 

- [x] For wireframe please list component names and functions you will need to define for each 

- [x]  Map out file structure based on wireframe. See ppt for sample https://docs.google.com/presentation/d/10-R4ZH1ep6YRNJ6fh_r_ZaCBMLXR0rplW-2X4VdEmXk/edit#slide=id.g7d19537126c9dbd0_0

- [x]  It is not necessary to use threejs for this project you can use just canvas and pure css/js.  You may want to start without using threejs to get game logic down and then add the 3d animation later.  
Some sample projects:
- https://github.com/masonanders/Wormhole
- https://github.com/yorkis-diaz/Myst-Fish

**Comment by RazEfron** [comment]
users will not be able to leave the game and come back to the same level as before, I might want to save highscores but as a bonus.

I updated the file, for the functions. components and file structure It still a little too vague for me to build.
